"""empty message

Revision ID: 99e99480527c
Revises: ad73e6b857ae
Create Date: 2020-06-24 20:54:39.549186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e99480527c'
down_revision = 'ad73e6b857ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('date', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('goal', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'goal')
    op.drop_column('requests', 'date')
    # ### end Alembic commands ###
